name: asha_prior-default-at-target
mf: true
run_function:
  _target_: mf_prior_experiments.run.run_neps
searcher:
  _partial_: true  # To not instantiate the class directly as required by neps
  _target_: neps.optimizers.multi_fidelity.successive_halving.AsynchronousSuccessiveHalvingWithPriors
  sample_default_first: True
  sample_default_at_target: True
