name: hb_inc-50
mf: true
run_function:
  _target_: mf_prior_experiments.run.run_neps
searcher:
  _partial_: true  # To not instantiate the class directly as required by neps
  _target_: neps.optimizers.multi_fidelity_prior.priorband.PriorBandNoPriorToInc
  prior_weight_type: 50-50
  inc_sample_type: crossover
  inc_style: dynamic
  model_based: False
  sample_default_first: False
