name: hpbandster
model: False
run_function:
  _target_: mf_prior_experiments.run.run_hpbandster
#searcher:
#  _partial_: true  # To not instantiate the class directly as required by neps
#  _target_: neps.optimizers.multi_fidelity.successive_halving.AsynchronousSuccessiveHalving
