name: priorband_hypersphere_constant
mf: true
run_function:
  _target_: mf_prior_experiments.run.run_neps
searcher:
  _partial_: true  # To not instantiate the class directly as required by neps
  _target_: neps.optimizers.multi_fidelity_prior.priorband.PriorBand
  prior_weight_type: geometric
  inc_sample_type: hypersphere
  inc_style: constant
