name: random_search_prior-no-default
mf: false
run_function:
  _target_: mf_prior_experiments.run.run_neps
searcher:
  _partial_: true  # To not instantiate the class directly as required by neps
  _target_: mf_prior_algorithms.random_search.RandomSearchWithPriors
  sample_default_first: False
