name: charLM-large_large_shakespeare
api:
  bench_name: charLM-large
  bench_size: large
  _target_: lmhpo.src.gpt_bench.CharLMBench
  seed: ${seed}
  set_defaults: true
budget:
  max: 5000
  min: 500