name: charLM-default_small_shakespeare
api:
  bench_name: charLM-default
  bench_size: small
  _target_: lmhpo.src.gpt_bench.CharLMBench
  seed: ${seed}
  set_defaults: true
budget:
  max: 3000
  min: 300