name: lcbench-167190_prior-gpt
api:
  name: lcbench
  prior: gpt
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '167190'
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: None
prior_lowest_error: None
best_10_error: None
best_25_error: None
best_50_error: None
best_90_error: None
best_100_error: None
